Enable use of Unix domain sockets
stepancheg/rust-http2 pull request #15
Opened 2017-08-02 02:51 UTC by bblancha

* Use traits to hide socket type from server and client loops
* Preserve tcp-based api, don't break current clients

2017-08-02 02:56 UTC, bblancha commented
I still need to check if this builds on Window.

2017-08-04 11:40 UTC, stepancheg commented on src/client.rs
> +    pub addr: Option<T>,
I think probably instead of type parameters field should be of enum type like

```
enum AnySocketAddr { Inet(...), Unix(...) }
```

2017-08-04 11:44 UTC, stepancheg commented on tests/test_misc/server_test_unix.rs
> +impl Service for Blocks {
This looks like copy-paste.

2017-08-04 11:45 UTC, stepancheg requested changes
Apart from minor changed I requested, it looks good.

2017-08-04 11:56 UTC, bblancha commented on tests/test_misc/server_test_unix.rs
> +impl Service for Blocks {
Yes, I copy-pasted the server_test.rs file, then made small changes to make a UDS ServerTest struct..
I will refactor them back together and clean up a little bit.

2017-08-04 23:10 UTC, bblancha commented
Still need to change interface of ClientBuilder to match ServerBuilder

2017-08-05 00:24 UTC, stepancheg commented on tests/server.rs
> +    let _server = ServerTest::new_unix("/tmp/rust_http2_test".to_owned());
Fixed path in `/tmp` is not ideal. Something like [that](https://github.com/rust-lang-nursery/tempdir) could be used.

2017-08-05 00:25 UTC, stepancheg commented on tests/test_misc/server_test.rs
> -
This change needs to be reverted.

2017-08-05 00:25 UTC, stepancheg approved these changes
There are minor issues with commit, but I'm going to squash and merge it now anyway.

2017-08-05 00:26 UTC, merged

2017-08-05 00:26 UTC, stepancheg commented
Do I understand correctly that grpc implementation based on this patch should be compatible with other grpc implementations over Unix sockets?

2017-08-05 00:26 UTC, bblancha commented
Sounds good, I will follow up with fixes in a few days.

2017-08-05 00:29 UTC, bblancha commented
Yes, I believe it will be compatible. I haven't tested interop yet, but will do so soon.